/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainlinkBasedOracle } from "./ChainlinkBasedOracle";
export type { IChainlinkAggregatorV2V3 } from "./IChainlinkAggregatorV2V3";
