/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStableIRM__factory } from "./IStableIRM__factory";
export { SpathaSetters__factory } from "./SpathaSetters__factory";
