/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChainlinkAggregatorV2V3 } from "./IChainlinkAggregatorV2V3";
export type { WBTCOracle } from "./WBTCOracle";
