/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISpatha__factory } from "./ISpatha__factory";
export { MarketBasedGovernance__factory } from "./MarketBasedGovernance__factory";
