/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IChainlinkAggregatorV2V3__factory } from "./IChainlinkAggregatorV2V3__factory";
export { WBTCOracle__factory } from "./WBTCOracle__factory";
