/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProtocolGovernance } from "./ProtocolGovernance";
export type { ProtocolTimelockController } from "./ProtocolTimelockController";
