/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Governable,
  GovernableInterface,
} from "../../../src/governance/Governable";

const _abi = [
  {
    inputs: [],
    name: "CALLER_NOT_GOVERNOR",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldGovernor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "LogGovernorSet",
    type: "event",
  },
  {
    inputs: [],
    name: "governor",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newGovernor",
        type: "address",
      },
    ],
    name: "transferGovernance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Governable__factory {
  static readonly abi = _abi;
  static createInterface(): GovernableInterface {
    return new Interface(_abi) as GovernableInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Governable {
    return new Contract(address, _abi, runner) as unknown as Governable;
  }
}
