/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type MarketParamsStruct = {
  loanToken: AddressLike;
  collateralToken: AddressLike;
  riskTier: BigNumberish;
  lltv: BigNumberish;
  irm: AddressLike;
};

export type MarketParamsStructOutput = [
  loanToken: string,
  collateralToken: string,
  riskTier: bigint,
  lltv: bigint,
  irm: string
] & {
  loanToken: string;
  collateralToken: string;
  riskTier: bigint;
  lltv: bigint;
  irm: string;
};

export type PauseStatusesStruct = {
  isAddLiquidityPaused: boolean;
  isAddCollateralPaused: boolean;
  isBorrowPaused: boolean;
  isWithdrawLiquidityPaused: boolean;
  isWithdrawCollateralPaused: boolean;
  isRepayPaused: boolean;
  isLiquidatePaused: boolean;
};

export type PauseStatusesStructOutput = [
  isAddLiquidityPaused: boolean,
  isAddCollateralPaused: boolean,
  isBorrowPaused: boolean,
  isWithdrawLiquidityPaused: boolean,
  isWithdrawCollateralPaused: boolean,
  isRepayPaused: boolean,
  isLiquidatePaused: boolean
] & {
  isAddLiquidityPaused: boolean;
  isAddCollateralPaused: boolean;
  isBorrowPaused: boolean;
  isWithdrawLiquidityPaused: boolean;
  isWithdrawCollateralPaused: boolean;
  isRepayPaused: boolean;
  isLiquidatePaused: boolean;
};

export type MarketStruct = {
  totalSupplyAssets: BigNumberish;
  totalSupplyShares: BigNumberish;
  totalBorrowAssets: BigNumberish;
  totalBorrowShares: BigNumberish;
  lastUpdate: BigNumberish;
  fee: BigNumberish;
  pauseStatuses: PauseStatusesStruct;
};

export type MarketStructOutput = [
  totalSupplyAssets: bigint,
  totalSupplyShares: bigint,
  totalBorrowAssets: bigint,
  totalBorrowShares: bigint,
  lastUpdate: bigint,
  fee: bigint,
  pauseStatuses: PauseStatusesStructOutput
] & {
  totalSupplyAssets: bigint;
  totalSupplyShares: bigint;
  totalBorrowAssets: bigint;
  totalBorrowShares: bigint;
  lastUpdate: bigint;
  fee: bigint;
  pauseStatuses: PauseStatusesStructOutput;
};

export interface VariableIRMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "SPATHA"
      | "borrowRate"
      | "borrowRateView"
      | "getMarketIdWithMarketParams"
      | "rateAtTarget"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "LogBorrowRateUpdate"): EventFragment;

  encodeFunctionData(functionFragment: "SPATHA", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowRate",
    values: [MarketParamsStruct, MarketStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowRateView",
    values: [MarketParamsStruct, MarketStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketIdWithMarketParams",
    values: [MarketParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAtTarget",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "SPATHA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrowRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowRateView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketIdWithMarketParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAtTarget",
    data: BytesLike
  ): Result;
}

export namespace LogBorrowRateUpdateEvent {
  export type InputTuple = [
    id: BytesLike,
    avgBorrowRate: BigNumberish,
    rateAtTarget: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    avgBorrowRate: bigint,
    rateAtTarget: bigint
  ];
  export interface OutputObject {
    id: string;
    avgBorrowRate: bigint;
    rateAtTarget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VariableIRM extends BaseContract {
  connect(runner?: ContractRunner | null): VariableIRM;
  waitForDeployment(): Promise<this>;

  interface: VariableIRMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  SPATHA: TypedContractMethod<[], [string], "view">;

  borrowRate: TypedContractMethod<
    [marketParams: MarketParamsStruct, market: MarketStruct],
    [bigint],
    "nonpayable"
  >;

  borrowRateView: TypedContractMethod<
    [marketParams: MarketParamsStruct, market: MarketStruct],
    [bigint],
    "view"
  >;

  getMarketIdWithMarketParams: TypedContractMethod<
    [marketParams: MarketParamsStruct],
    [string],
    "view"
  >;

  rateAtTarget: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "SPATHA"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "borrowRate"
  ): TypedContractMethod<
    [marketParams: MarketParamsStruct, market: MarketStruct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrowRateView"
  ): TypedContractMethod<
    [marketParams: MarketParamsStruct, market: MarketStruct],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketIdWithMarketParams"
  ): TypedContractMethod<[marketParams: MarketParamsStruct], [string], "view">;
  getFunction(
    nameOrSignature: "rateAtTarget"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "LogBorrowRateUpdate"
  ): TypedContractEvent<
    LogBorrowRateUpdateEvent.InputTuple,
    LogBorrowRateUpdateEvent.OutputTuple,
    LogBorrowRateUpdateEvent.OutputObject
  >;

  filters: {
    "LogBorrowRateUpdate(bytes32,uint256,uint256)": TypedContractEvent<
      LogBorrowRateUpdateEvent.InputTuple,
      LogBorrowRateUpdateEvent.OutputTuple,
      LogBorrowRateUpdateEvent.OutputObject
    >;
    LogBorrowRateUpdate: TypedContractEvent<
      LogBorrowRateUpdateEvent.InputTuple,
      LogBorrowRateUpdateEvent.OutputTuple,
      LogBorrowRateUpdateEvent.OutputObject
    >;
  };
}
