/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as priceOracleSol from "./PriceOracle.sol";
export type { priceOracleSol };
import type * as wbtcOracleSol from "./WBTCOracle.sol";
export type { wbtcOracleSol };
import type * as wstethOracleSol from "./WSTETHOracle.sol";
export type { wstethOracleSol };
import type * as chainlinkBasedOracleSol from "./chainlinkBasedOracle.sol";
export type { chainlinkBasedOracleSol };
