/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  SubAccountLib,
  SubAccountLibInterface,
} from "../../../src/libraries/SubAccountLib";

const _abi = [
  {
    inputs: [],
    name: "SubAccountIdOutOfBounds",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220df1b08f060fd047751a03d28ccf9c7b594f24c77159a3a9d1e2d83ccbd09ff8364736f6c63430008180033";

type SubAccountLibConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SubAccountLibConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SubAccountLib__factory extends ContractFactory {
  constructor(...args: SubAccountLibConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SubAccountLib & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SubAccountLib__factory {
    return super.connect(runner) as SubAccountLib__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SubAccountLibInterface {
    return new Interface(_abi) as SubAccountLibInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SubAccountLib {
    return new Contract(address, _abi, runner) as unknown as SubAccountLib;
  }
}
