/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iSpathaSol from "./ISpatha.sol";
export { IChainlinkAggregator__factory } from "./IChainlinkAggregator__factory";
export { IFallbackPriceOracle__factory } from "./IFallbackPriceOracle__factory";
export { IFallbackPriceOracleGetter__factory } from "./IFallbackPriceOracleGetter__factory";
export { IIrm__factory } from "./IIrm__factory";
export { IPriceOracle__factory } from "./IPriceOracle__factory";
export { IStableIrm__factory } from "./IStableIrm__factory";
export { IVariableIrm__factory } from "./IVariableIrm__factory";
