/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as protocolGovernance from "./protocol-governance";
export type { protocolGovernance };
import type * as subGovernance from "./sub-governance";
export type { subGovernance };
import type * as votingStrategies from "./voting-strategies";
export type { votingStrategies };
export type { Governable } from "./Governable";
