/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISpatha } from "./ISpatha";
export type { MarketBasedGovernance } from "./MarketBasedGovernance";
