/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as quadraticVotingStrategySol from "./QuadraticVotingStrategy.sol";
export type { quadraticVotingStrategySol };
export type { HarmonicVotingStrategy } from "./HarmonicVotingStrategy";
export type { IVotingStrategy } from "./IVotingStrategy";
export type { LinearVotingStrategy } from "./LinearVotingStrategy";
export type { LogarithmicVotingStrategy } from "./LogarithmicVotingStrategy";
export type { PointsVotingStrategy } from "./PointsVotingStrategy";
