/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMulticall__factory } from "./IMulticall__factory";
export { Multicall__factory } from "./Multicall__factory";
