/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSpathaSol from "./ISpatha.sol";
export type { iSpathaSol };
export type { IChainlinkAggregator } from "./IChainlinkAggregator";
export type { IFallbackPriceOracle } from "./IFallbackPriceOracle";
export type { IFallbackPriceOracleGetter } from "./IFallbackPriceOracleGetter";
export type { IIrm } from "./IIrm";
export type { IPriceOracle } from "./IPriceOracle";
export type { IStableIrm } from "./IStableIrm";
export type { IVariableIrm } from "./IVariableIrm";
