/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IChainlinkAggregatorV2V3,
  IChainlinkAggregatorV2V3Interface,
} from "../../../../src/oracles/WSTETHOracle.sol/IChainlinkAggregatorV2V3";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "description",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestAnswer",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "latestTimestamp",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IChainlinkAggregatorV2V3__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkAggregatorV2V3Interface {
    return new Interface(_abi) as IChainlinkAggregatorV2V3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IChainlinkAggregatorV2V3 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IChainlinkAggregatorV2V3;
  }
}
