/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStETH,
  IStETHInterface,
} from "../../../../src/oracles/WSTETHOracle.sol/IStETH";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_sharesAmount",
        type: "uint256",
      },
    ],
    name: "getPooledEthByShares",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStETH__factory {
  static readonly abi = _abi;
  static createInterface(): IStETHInterface {
    return new Interface(_abi) as IStETHInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IStETH {
    return new Contract(address, _abi, runner) as unknown as IStETH;
  }
}
