/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20Votes__factory } from "./IERC20Votes__factory";
export { TreasuryVester__factory } from "./TreasuryVester__factory";
